### ISSUE TITLE
How many patches are generated per fault localization?

### ISSUE THREAD

**Issue by cc32** [SerVal-DTF/iFixR#2]
Hi, I have a question about the experiment setting of patch generation. In the 5.2 section(RQ2), when invesgating the impact of localization bias, top-k fault localization are used for patch generation. 
However, it seems that the number of generated patch for each fault localization is not posed in the paper, and I don't find it in this repository either. I wonder if it is writted in code and I miss it. Thanks.

**Comment by anilkoyuncu** [comment]
Hello,
Can you elaborate on what you mean exactly by "the number of generated patches for each fault localization"?
We keep the the position the correct/plausible patch.
For example, if you go to the [following folder](https://github.com/TruX-DTF/iFixR/tree/master/OUTPUT/MIMIC/FixedBugs/Lang_10) you would find the patch generated for Lang_10. 
The name of the file ([Patch_898.txt](https://github.com/TruX-DTF/iFixR/blob/master/OUTPUT/MIMIC/FixedBugs/Lang_10/Patch_898.txt)) indicates the position of the patch. 
The position of the patch (898) is calculated based on the previously generated non-plausible patch candidates (e.g., Lang_10 Patch_898 means that we generate 897 patches until we find this plausible patch).

**Comment by cc32** [comment]
> Hello, Can you elaborate on what you mean exactly by "the number of generated patches for each fault localization"? We keep the the position the correct/plausible patch. For example, if you go to the [following folder](https://github.com/TruX-DTF/iFixR/tree/master/OUTPUT/MIMIC/FixedBugs/Lang_10) you would find the patch generated for Lang_10. The name of the file ([Patch_898.txt](https://github.com/TruX-DTF/iFixR/blob/master/OUTPUT/MIMIC/FixedBugs/Lang_10/Patch_898.txt)) indicates the position of the patch. The position of the patch (898) is calculated based on the previously generated non-plausible patch candidates (e.g., Lang_10 Patch_898 means that we generate 897 patches until we find this plausible patch).

Thanks for your quick reply! I have figured out this problem now.
