### ISSUE TITLE
some issues about config environment

### ISSUE THREAD

**Issue by lemon1-ui** [SerVal-DTF/iFixR#3]
Hello, How should I proceed with 'Clone the repository' in the Docker section of the readme file when configuring the environment? What is the function of Docker?

**Comment by anilkoyuncu** [comment]
Hello,
The docker image needs repository as a volume. 

docker run -v <path_of_cloned_repository>/:/data -it anilkoyuncu/ifixr:latest /bin/bash

**Comment by lemon1-ui** [comment]
@anilkoyuncu Hi, I'm so sorry to bother you again. What are the screening criteria for defect reports?
