### ISSUE TITLE
Error message while replicating the work

### ISSUE THREAD

**Issue by aiyaya50** [SerVal-DTF/iFixR#4]
Hi
I have been trying to replicate the work but have been receiving same error message to all the jobs type.

You may note that  I received error message regarding sklearn which disappered after installing sci-kit learn module. 
see the error messages below for your help.

Thank you

(base) aiyaya50@APR:~/iFixR$ bash startPy.sh /home/aiyaya50/iFixR/ fix Lang
Collecting en-core-web-lg==3.8.0
  Downloading https://github.com/explosion/spacy-models/releases/download/en_core_web_lg-3.8.0/en_core_web_lg-3.8.0-py3-none-any.whl (400.7 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 400.7/400.7 MB 2.6 MB/s eta 0:00:00
Installing collected packages: en-core-web-lg
Successfully installed en-core-web-lg-3.8.0
✔ Download and installation successful
You can now load the package via spacy.load('en_core_web_lg')
2024-11-09 14:37:44,680 - 312551 - ERROR - launcherSingle.py:<module> - load() missing 1 required positional argument: 'Loader'
(base) aiyaya50@APR:~/iFixR$ bash startPy.sh /home/aiyaya50/iFixR/ bugPoints Lang
Collecting en-core-web-lg==3.8.0
  Downloading https://github.com/explosion/spacy-models/releases/download/en_core_web_lg-3.8.0/en_core_web_lg-3.8.0-py3-none-any.whl (400.7 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 400.7/400.7 MB 3.3 MB/s eta 0:00:00
✔ Download and installation successful
You can now load the package via spacy.load('en_core_web_lg')
2024-11-09 14:42:17,242 - 314066 - ERROR - launcherSingle.py:<module> - load() missing 1 required positional argument: 'Loader'

**Comment by anilkoyuncu** [comment]
Hello,
The error seems related to Spacy load. You can check the following so post for the solution.

https://stackoverflow.com/questions/56470403/spacy-nlp-spacy-loaden-core-web-lg
